export interface Piexif {
  /**
   * Get exif data as object. jpegData must be a string that starts with "data:image/jpeg;base64,"(DataURL), "\xff\xd8", or "Exif".
   * @param jpegData 
   */
  load(jpegData: string): any
  /**
   * Get exif as string to insert into JPEG.
   * @param exifObj 
   */
  dump(exifObj: any): string
  /**
   * Insert exif into JPEG. If jpegData is DataURL, returns JPEG as DataURL. Else if jpegData is binary as string, returns JPEG as binary as string.
   * @param exifStr 
   * @param jpegData 
   */
  insert(exifStr: string, jpegData: string): string
  /**
   * Remove exif from JPEG. If jpegData is DataURL, returns JPEG as DataURL. Else if jpegData is binary as string, returns JPEG as binary as string.
   * @param jpegData 
   */
  remove(jpegData: string): any
  ImageIFD: ImageIFD
  ExifIFD: ExifIFD
  GPSIFD: GPSIFD
}

export const ImageIFDProperties: string[] = ["ProcessingSoftware", "NewSubfileType", "SubfileType", "ImageWidth", "ImageLength", "BitsPerSample", "Compression", "PhotometricInterpretation", "Threshholding", "CellWidth", "CellLength", "FillOrder", "DocumentName", "ImageDescription", "Make", "Model", "StripOffsets", "Orientation", "SamplesPerPixel", "RowsPerStrip", "StripByteCounts", "XResolution", "YResolution", "PlanarConfiguration", "GrayResponseUnit", "GrayResponseCurve", "T4Options", "T6Options", "ResolutionUnit", "TransferFunction", "Software", "DateTime", "Artist", "HostComputer", "Predictor", "WhitePoint", "PrimaryChromaticities", "ColorMap", "HalftoneHints", "TileWidth", "TileLength", "TileOffsets", "TileByteCounts", "SubIFDs", "InkSet", "InkNames", "NumberOfInks", "DotRange", "TargetPrinter", "ExtraSamples", "SampleFormat", "SMinSampleValue", "SMaxSampleValue", "TransferRange", "ClipPath", "XClipPathUnits", "YClipPathUnits", "Indexed", "JPEGTables", "OPIProxy", "JPEGProc", "JPEGInterchangeFormat", "JPEGInterchangeFormatLength", "JPEGRestartInterval", "JPEGLosslessPredictors", "JPEGPointTransforms", "JPEGQTables", "JPEGDCTables", "JPEGACTables", "YCbCrCoefficients", "YCbCrSubSampling", "YCbCrPositioning", "ReferenceBlackWhite", "XMLPacket", "Rating", "RatingPercent", "ImageID", "CFARepeatPatternDim", "CFAPattern", "BatteryLevel", "Copyright", "ExposureTime", "ImageResources", "ExifTag", "InterColorProfile", "GPSTag", "Interlace", "TimeZoneOffset", "SelfTimerMode", "FlashEnergy", "SpatialFrequencyResponse", "Noise", "FocalPlaneXResolution", "FocalPlaneYResolution", "FocalPlaneResolutionUnit", "ImageNumber", "SecurityClassification", "ImageHistory", "ExposureIndex", "TIFFEPStandardID", "SensingMethod", "XPTitle", "XPComment", "XPAuthor", "XPKeywords", "XPSubject", "PrintImageMatching", "DNGVersion", "DNGBackwardVersion", "UniqueCameraModel", "LocalizedCameraModel", "CFAPlaneColor", "CFALayout", "LinearizationTable", "BlackLevelRepeatDim", "BlackLevel", "BlackLevelDeltaH", "BlackLevelDeltaV", "WhiteLevel", "DefaultScale", "DefaultCropOrigin", "DefaultCropSize", "ColorMatrix1", "ColorMatrix2", "CameraCalibration1", "CameraCalibration2", "ReductionMatrix1", "ReductionMatrix2", "AnalogBalance", "AsShotNeutral", "AsShotWhiteXY", "BaselineExposure", "BaselineNoise", "BaselineSharpness", "BayerGreenSplit", "LinearResponseLimit", "CameraSerialNumber", "LensInfo", "ChromaBlurRadius", "AntiAliasStrength", "ShadowScale", "DNGPrivateData", "MakerNoteSafety", "CalibrationIlluminant1", "CalibrationIlluminant2", "BestQualityScale", "RawDataUniqueID", "OriginalRawFileName", "OriginalRawFileData", "ActiveArea", "MaskedAreas", "AsShotICCProfile", "AsShotPreProfileMatrix", "CurrentICCProfile", "CurrentPreProfileMatrix", "ColorimetricReference", "CameraCalibrationSignature", "ProfileCalibrationSignature", "AsShotProfileName", "NoiseReductionApplied", "ProfileName", "ProfileHueSatMapDims", "ProfileHueSatMapData1", "ProfileHueSatMapData2", "ProfileToneCurve", "ProfileEmbedPolicy", "ProfileCopyright", "ForwardMatrix1", "ForwardMatrix2", "PreviewApplicationName", "PreviewApplicationVersion", "PreviewSettingsName", "PreviewSettingsDigest", "PreviewColorSpace", "PreviewDateTime", "RawImageDigest", "OriginalRawFileDigest", "SubTileBlockSize", "RowInterleaveFactor", "ProfileLookTableDims", "ProfileLookTableData", "OpcodeList1", "OpcodeList2", "OpcodeList3", "NoiseProfile"]
export interface ImageIFD {
  ProcessingSoftware: 11,
  NewSubfileType: 254,
  SubfileType: 255,
  ImageWidth: 256,
  ImageLength: 257,
  BitsPerSample: 258,
  Compression: 259,
  PhotometricInterpretation: 262,
  Threshholding: 263,
  CellWidth: 264,
  CellLength: 265,
  FillOrder: 266,
  DocumentName: 269,
  ImageDescription: 270,
  Make: 271,
  Model: 272,
  StripOffsets: 273,
  Orientation: 274,
  SamplesPerPixel: 277,
  RowsPerStrip: 278,
  StripByteCounts: 279,
  XResolution: 282,
  YResolution: 283,
  PlanarConfiguration: 284,
  GrayResponseUnit: 290,
  GrayResponseCurve: 291,
  T4Options: 292,
  T6Options: 293,
  ResolutionUnit: 296,
  TransferFunction: 301,
  Software: 305,
  DateTime: 306,
  Artist: 315,
  HostComputer: 316,
  Predictor: 317,
  WhitePoint: 318,
  PrimaryChromaticities: 319,
  ColorMap: 320,
  HalftoneHints: 321,
  TileWidth: 322,
  TileLength: 323,
  TileOffsets: 324,
  TileByteCounts: 325,
  SubIFDs: 330,
  InkSet: 332,
  InkNames: 333,
  NumberOfInks: 334,
  DotRange: 336,
  TargetPrinter: 337,
  ExtraSamples: 338,
  SampleFormat: 339,
  SMinSampleValue: 340,
  SMaxSampleValue: 341,
  TransferRange: 342,
  ClipPath: 343,
  XClipPathUnits: 344,
  YClipPathUnits: 345,
  Indexed: 346,
  JPEGTables: 347,
  OPIProxy: 351,
  JPEGProc: 512,
  JPEGInterchangeFormat: 513,
  JPEGInterchangeFormatLength: 514,
  JPEGRestartInterval: 515,
  JPEGLosslessPredictors: 517,
  JPEGPointTransforms: 518,
  JPEGQTables: 519,
  JPEGDCTables: 520,
  JPEGACTables: 521,
  YCbCrCoefficients: 529,
  YCbCrSubSampling: 530,
  YCbCrPositioning: 531,
  ReferenceBlackWhite: 532,
  XMLPacket: 700,
  Rating: 18246,
  RatingPercent: 18249,
  ImageID: 32781,
  CFARepeatPatternDim: 33421,
  CFAPattern: 33422,
  BatteryLevel: 33423,
  Copyright: 33432,
  ExposureTime: 33434,
  ImageResources: 34377,
  ExifTag: 34665,
  InterColorProfile: 34675,
  GPSTag: 34853,
  Interlace: 34857,
  TimeZoneOffset: 34858,
  SelfTimerMode: 34859,
  FlashEnergy: 37387,
  SpatialFrequencyResponse: 37388,
  Noise: 37389,
  FocalPlaneXResolution: 37390,
  FocalPlaneYResolution: 37391,
  FocalPlaneResolutionUnit: 37392,
  ImageNumber: 37393,
  SecurityClassification: 37394,
  ImageHistory: 37395,
  ExposureIndex: 37397,
  TIFFEPStandardID: 37398,
  SensingMethod: 37399,
  XPTitle: 40091,
  XPComment: 40092,
  XPAuthor: 40093,
  XPKeywords: 40094,
  XPSubject: 40095,
  PrintImageMatching: 50341,
  DNGVersion: 50706,
  DNGBackwardVersion: 50707,
  UniqueCameraModel: 50708,
  LocalizedCameraModel: 50709,
  CFAPlaneColor: 50710,
  CFALayout: 50711,
  LinearizationTable: 50712,
  BlackLevelRepeatDim: 50713,
  BlackLevel: 50714,
  BlackLevelDeltaH: 50715,
  BlackLevelDeltaV: 50716,
  WhiteLevel: 50717,
  DefaultScale: 50718,
  DefaultCropOrigin: 50719,
  DefaultCropSize: 50720,
  ColorMatrix1: 50721,
  ColorMatrix2: 50722,
  CameraCalibration1: 50723,
  CameraCalibration2: 50724,
  ReductionMatrix1: 50725,
  ReductionMatrix2: 50726,
  AnalogBalance: 50727,
  AsShotNeutral: 50728,
  AsShotWhiteXY: 50729,
  BaselineExposure: 50730,
  BaselineNoise: 50731,
  BaselineSharpness: 50732,
  BayerGreenSplit: 50733,
  LinearResponseLimit: 50734,
  CameraSerialNumber: 50735,
  LensInfo: 50736,
  ChromaBlurRadius: 50737,
  AntiAliasStrength: 50738,
  ShadowScale: 50739,
  DNGPrivateData: 50740,
  MakerNoteSafety: 50741,
  CalibrationIlluminant1: 50778,
  CalibrationIlluminant2: 50779,
  BestQualityScale: 50780,
  RawDataUniqueID: 50781,
  OriginalRawFileName: 50827,
  OriginalRawFileData: 50828,
  ActiveArea: 50829,
  MaskedAreas: 50830,
  AsShotICCProfile: 50831,
  AsShotPreProfileMatrix: 50832,
  CurrentICCProfile: 50833,
  CurrentPreProfileMatrix: 50834,
  ColorimetricReference: 50879,
  CameraCalibrationSignature: 50931,
  ProfileCalibrationSignature: 50932,
  AsShotProfileName: 50934,
  NoiseReductionApplied: 50935,
  ProfileName: 50936,
  ProfileHueSatMapDims: 50937,
  ProfileHueSatMapData1: 50938,
  ProfileHueSatMapData2: 50939,
  ProfileToneCurve: 50940,
  ProfileEmbedPolicy: 50941,
  ProfileCopyright: 50942,
  ForwardMatrix1: 50964,
  ForwardMatrix2: 50965,
  PreviewApplicationName: 50966,
  PreviewApplicationVersion: 50967,
  PreviewSettingsName: 50968,
  PreviewSettingsDigest: 50969,
  PreviewColorSpace: 50970,
  PreviewDateTime: 50971,
  RawImageDigest: 50972,
  OriginalRawFileDigest: 50973,
  SubTileBlockSize: 50974,
  RowInterleaveFactor: 50975,
  ProfileLookTableDims: 50981,
  ProfileLookTableData: 50982,
  OpcodeList1: 51008,
  OpcodeList2: 51009,
  OpcodeList3: 51022,
  NoiseProfile: 51041,
}

export const ExifIFDProperties: string[] = ["ExposureTime", "FNumber", "ExposureProgram", "SpectralSensitivity", "ISOSpeedRatings", "OECF", "SensitivityType", "StandardOutputSensitivity", "RecommendedExposureIndex", "ISOSpeed", "ISOSpeedLatitudeyyy", "ISOSpeedLatitudezzz", "ExifVersion", "DateTimeOriginal", "DateTimeDigitized", "ComponentsConfiguration", "CompressedBitsPerPixel", "ShutterSpeedValue", "ApertureValue", "BrightnessValue", "ExposureBiasValue", "MaxApertureValue", "SubjectDistance", "MeteringMode", "LightSource", "Flash", "FocalLength", "SubjectArea", "MakerNote", "UserComment", "SubSecTime", "SubSecTimeOriginal", "SubSecTimeDigitized", "FlashpixVersion", "ColorSpace", "PixelXDimension", "PixelYDimension", "RelatedSoundFile", "InteroperabilityTag", "FlashEnergy", "SpatialFrequencyResponse", "FocalPlaneXResolution", "FocalPlaneYResolution", "FocalPlaneResolutionUnit", "SubjectLocation", "ExposureIndex", "SensingMethod", "FileSource", "SceneType", "CFAPattern", "CustomRendered", "ExposureMode", "WhiteBalance", "DigitalZoomRatio", "FocalLengthIn35mmFilm", "SceneCaptureType", "GainControl", "Contrast", "Saturation", "Sharpness", "DeviceSettingDescription", "SubjectDistanceRange", "ImageUniqueID", "CameraOwnerName", "BodySerialNumber", "LensSpecification", "LensMake", "LensModel", "LensSerialNumber", "Gamma"]
export interface ExifIFD {ExposureTime:33434,
  FNumber:33437,
  ExposureProgram:34850,
  SpectralSensitivity:34852,
  ISOSpeedRatings:34855,
  OECF:34856,
  SensitivityType:34864,
  StandardOutputSensitivity:34865,
  RecommendedExposureIndex:34866,
  ISOSpeed:34867,
  ISOSpeedLatitudeyyy:34868,
  ISOSpeedLatitudezzz:34869,
  ExifVersion:36864,
  DateTimeOriginal:36867,
  DateTimeDigitized:36868,
  ComponentsConfiguration:37121,
  CompressedBitsPerPixel:37122,
  ShutterSpeedValue:37377,
  ApertureValue:37378,
  BrightnessValue:37379,
  ExposureBiasValue:37380,
  MaxApertureValue:37381,
  SubjectDistance:37382,
  MeteringMode:37383,
  LightSource:37384,
  Flash:37385,
  FocalLength:37386,
  SubjectArea:37396,
  MakerNote:37500,
  UserComment:37510,
  SubSecTime:37520,
  SubSecTimeOriginal:37521,
  SubSecTimeDigitized:37522,
  FlashpixVersion:40960,
  ColorSpace:40961,
  PixelXDimension:40962,
  PixelYDimension:40963,
  RelatedSoundFile:40964,
  InteroperabilityTag:40965,
  FlashEnergy:41483,
  SpatialFrequencyResponse:41484,
  FocalPlaneXResolution:41486,
  FocalPlaneYResolution:41487,
  FocalPlaneResolutionUnit:41488,
  SubjectLocation:41492,
  ExposureIndex:41493,
  SensingMethod:41495,
  FileSource:41728,
  SceneType:41729,
  CFAPattern:41730,
  CustomRendered:41985,
  ExposureMode:41986,
  WhiteBalance:41987,
  DigitalZoomRatio:41988,
  FocalLengthIn35mmFilm:41989,
  SceneCaptureType:41990,
  GainControl:41991,
  Contrast:41992,
  Saturation:41993,
  Sharpness:41994,
  DeviceSettingDescription:41995,
  SubjectDistanceRange:41996,
  ImageUniqueID:42016,
  CameraOwnerName:42032,
  BodySerialNumber:42033,
  LensSpecification:42034,
  LensMake:42035,
  LensModel:42036,
  LensSerialNumber:42037,
  Gamma:42240,
}

export const GPSIFDProperties: string[] = ["GPSVersionID", "GPSLatitudeRef", "GPSLatitude", "GPSLongitudeRef", "GPSLongitude", "GPSAltitudeRef", "GPSAltitude", "GPSTimeStamp", "GPSSatellites", "GPSStatus", "GPSMeasureMode", "GPSDOP", "GPSSpeedRef", "GPSSpeed", "GPSTrackRef", "GPSTrack", "GPSImgDirectionRef", "GPSImgDirection", "GPSMapDatum", "GPSDestLatitudeRef", "GPSDestLatitude", "GPSDestLongitudeRef", "GPSDestLongitude", "GPSDestBearingRef", "GPSDestBearing", "GPSDestDistanceRef", "GPSDestDistance", "GPSProcessingMethod", "GPSAreaInformation", "GPSDateStamp", "GPSDifferential", "GPSHPositioningError"]
export interface GPSIFD {
  GPSVersionID:0,
  GPSLatitudeRef:1,
  GPSLatitude:2,
  GPSLongitudeRef:3,
  GPSLongitude:4,
  GPSAltitudeRef:5,
  GPSAltitude:6,
  GPSTimeStamp:7,
  GPSSatellites:8,
  GPSStatus:9,
  GPSMeasureMode:10,
  GPSDOP:11,
  GPSSpeedRef:12,
  GPSSpeed:13,
  GPSTrackRef:14,
  GPSTrack:15,
  GPSImgDirectionRef:16,
  GPSImgDirection:17,
  GPSMapDatum:18,
  GPSDestLatitudeRef:19,
  GPSDestLatitude:20,
  GPSDestLongitudeRef:21,
  GPSDestLongitude:22,
  GPSDestBearingRef:23,
  GPSDestBearing:24,
  GPSDestDistanceRef:25,
  GPSDestDistance:26,
  GPSProcessingMethod:27,
  GPSAreaInformation:28,
  GPSDateStamp:29,
  GPSDifferential:30,
  GPSHPositioningError:31,
}